### ISSUE TITLE
how to download dataset

### ISSUE THREAD

**Issue by nashihu** [thorhu/Eyeblink-in-the-wild#1]
Hello. Thanks for sharing this repository

I have a request, would you like to share the dataset to a public drive? i have read that the dataset could be downloaded from [here](https://pan.baidu.com/s/1kyqVkzVVG-sYIaBOwr5pDQ#list/path=%2F) but unfortunately i can't download them because it requires Baidu account and i can't sign up a new account because i don't have a China's phone number as the prerequisite for creating a new account.

Thank you for your attention

**Comment by nashihu** [comment]
nevermind. I have used third party to download the 11.1GB files. 

Thank you for sharing the dataset. We really appreciate it

**Comment by VisualcampAiden** [comment]
Hello. Thanks for sharing this repository

I want to download this dataset for research, can you share it?

**Comment by fodorad** [comment]
Hello @nashihu, 

> nevermind. I have used third party to download the 11.1GB files.

Could you please show me the way how to get the dataset? 
I have difficulties registering to the Baidu site, and the authors failed to upload the dataset to the mentioned link for open access (Mega).

I would appreciate your kind help!

**Comment by nashihu** [comment]
@fodorad check it [here](https://www.buydiscountsoftwareonline.com) hope the site still running

**Comment by TrussedBoat** [comment]
@fodorad @nashihu 
Hello guys!
Any of you still have the full dataset stored somewhere?
Baidu is not giving me easy time and the link @nashihu gave is not working anymore

**Comment by fodorad** [comment]
> [@fodorad](https://github.com/fodorad) [@nashihu](https://github.com/nashihu) Hello guys! Any of you still have the full dataset stored somewhere? Baidu is not giving me easy time and the link [@nashihu](https://github.com/nashihu) gave is not working anymore

Unfortunately, I couldn't get the data in time, and I moved to my next research topic. For hobby research, however, I am still interested in this dataset.

**Comment by nashihu** [comment]
@TrussedBoat yes i still have it on my disk

give me some time to make it available online

**Comment by nashihu** [comment]
it was long upload session, hope the file still works fine

here @TrussedBoat @fodorad 

https://drive.google.com/file/d/1w1IWIMv3YiLQuEPPtKwnu4RLLTUPbLvr/view?usp=drive_link

**Comment by TrussedBoat** [comment]
Dude! Your are awesome. Thanks for that :)

**Comment by fodorad** [comment]
Awesome! Thank you! I will have another project to work on now ^^
